"use client";

import React from "react";

/**
 * NewUserPage component
 * This component provides a form for creating a new user.
 * It takes an optional username parameter but will generate a new user regardless of the parameter.
 * If the name is present it will be used as the username.
 * All other user data will be generated by the server.
 * @returns A React component for creating a new user.
 * @private [DEV] This page is only for development purposes and should not be used in production.
 */
export default function NewUserPage() {
  return (
    <div className="max-w-md mx-auto p-6 space-y-6">
      <h1 className="text-2xl font-bold">Create New User</h1>

      <form method="POST" action="/api/users/new" className="flex flex-col gap-4">
        <label className="block">
          <span className="text-sm font-medium">Name</span>
          <input
            type="text"
            name="username"
            className="mt-1 block w-full border rounded p-2"
            placeholder="username"
          />
        </label>

        <button
          type="submit"
          className="mt-2 bg-blue-600 text-white font-medium py-2 rounded"
        >
          Create User
        </button>
      </form>
    </div>
  );
}