"use client";

import React from "react";
import { Container, Box, Typography, TextField, Button } from "@mui/material";

/**
 * NewUserPage component
 * This component provides a form for creating a new user.
 * It takes an optional username parameter but will generate a new user regardless of the parameter.
 * If the name is present it will be used as the username.
 * All other user data will be generated by the server.
 * @returns A React component for creating a new user.
 * @private [DEV] This page is only for development purposes and should not be used in production.
 */
export default function NewUserPage() {
	return (
		<Container maxWidth="sm" sx={{ pt: 8 }}>
			<Typography variant="h4" component="h1" gutterBottom>
				Create New User
			</Typography>

			<Box
				component="form"
				method="POST"
				action="/api/api/v1/users/new"
				sx={{ display: "flex", flexDirection: "column", gap: 2 }}
			>
				<TextField
					label="Username"
					name="username"
					placeholder="username"
					variant="outlined"
					fullWidth
				/>

				<Button type="submit" variant="contained">
					Create User
				</Button>
			</Box>
			<Typography variant="h4" component="h1" gutterBottom>
				Create New Users
			</Typography>

			<Box
				component="form"
				method="POST"
				action="/api/api/v1/admin/gcx/"
				sx={{ display: "flex", flexDirection: "column", gap: 2 }}
			>
				<TextField
					label="Number of Users"
					name="num_users"
					placeholder="Number of Users"
					variant="outlined"
					fullWidth
				/>

				<Button type="submit" variant="contained">
					Create Users
				</Button>
			</Box>

			<Typography variant="h4" component="h1" gutterBottom>
				Delete Dummy Users
			</Typography>

			<Box
				component="form"
				method="POST"
				action="/api/api/v1/admin/dcx/"
				sx={{ display: "flex", flexDirection: "column", gap: 2 }}
			>
				<TextField
					label="Number of Users"
					name="num_users"
					placeholder="Number of Users"
					variant="outlined"
					fullWidth
				/>

				<Button type="submit" variant="contained">
					Delete Users
				</Button>
			</Box>
		</Container>
	);
}
